### ISSUE TITLE
使用0.1.0版本后无法初始化Accessory

### ISSUE THREAD

**Issue by chao** [YinHangCode/homebridge-mi-airpurifier#5]
我有一个空气净化器2，和净化器Pro，使用0.0.9版本一切正常。升级到0.1.0后能找到两个devices，但是accessory只有0个。

**Comment by YinHangCode** [comment]
type要改一下 前面加了Mi

**Comment by chao** [comment]
奥，没仔细看ChangeLog。

**Comment by YinHangCode** [comment]
嗯 0.1.0改了。。 因为类名相同会出问题 所以我让出airpurifier这个名字，用Miairpurifier 毕竟airpurifier这个含义太大了。。。
